apiVersion: apps/v1
kind: Deployment
metadata:
    name: productsapp-deployment
spec:
    selector:
        matchLabels: 
            app: productsapp
    template:
        metadata:
            labels:
                app: productsapp
    replicas: 3
    spec:
        containers:
            - name: productsapp-web
            image: BaseDockerfile
            args:
                - 
            ports:
                - containerPorts: 88
            